apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployments.yaml
configMapGenerator:
  - name: prometheus-config
    files:
      - prometheus.yml
  - name: grafana-datasources
    files:
      - datasource.yaml
  - name: grafana-providers
    files:
      - dashboards.yaml
  - name: grafana-dashboard
    files:
      - fcg-http.json
